language: python

matrix:
  include:
  - python: 2.7
  - python: 3.6
  - python: 3.7
    sudo: required
    dist: xenial

install:
  - pip install -r requirements.txt
  - pip install -e .
  - wget --user=HITRAN --password=getdata -N https://www.cfa.harvard.edu/HITRAN/HITEMP-2010/CO2_line_list/02_03750-04000_HITEMP2010.zip
  - wget --user=HITRAN --password=getdata -N https://www.cfa.harvard.edu/HITRAN/HITEMP-2010/CO2_line_list/02_04000-04500_HITEMP2010.zip
  - mv *.zip tests/

  - wget http://www.exomol.com/db/NH3/14N-1H3/BYTe/14N-1H3__BYTe__00100-00200.trans.bz2
  - wget http://www.exomol.com/db/NH3/14N-1H3/BYTe/14N-1H3__BYTe__00200-00300.trans.bz2
  - wget http://www.exomol.com/db/NH3/14N-1H3/BYTe/14N-1H3__BYTe.states.bz2
  - wget http://www.exomol.com/db/NH3/15N-1H3/BYTe-15/15N-1H3__BYTe-15__00100-00200.trans.bz2
  - wget http://www.exomol.com/db/NH3/15N-1H3/BYTe-15/15N-1H3__BYTe-15__00200-00300.trans.bz2
  - wget http://www.exomol.com/db/NH3/15N-1H3/BYTe-15/15N-1H3__BYTe-15.states.bz2
  - mv *.bz2 tests/

  - wget http://www.exomol.com/db/NH3/14N-1H3/BYTe/14N-1H3__BYTe.pf
  - wget http://www.exomol.com/db/NH3/15N-1H3/BYTe-15/15N-1H3__BYTe-15.pf
  - mv *.pf tests/

script: pytest tests
