language: python

matrix:
  include:
  - python: 2.7
  - python: 3.6
  - python: 3.7
    sudo: required
    dist: xenial

install:
  - pip install -r requirements.txt
  - pip install -e .
  - wget --user=HITRAN --password=getdata -N https://www.cfa.harvard.edu/HITRAN/HITEMP-2010/CO2_line_list/02_03750-04000_HITEMP2010.zip
  - wget --user=HITRAN --password=getdata -N https://www.cfa.harvard.edu/HITRAN/HITEMP-2010/CO2_line_list/02_04000-04500_HITEMP2010.zip && unzip 02_04000-04500_HITEMP2010.zip -d tests/
  - ls

script: pytest
